### ISSUE TITLE
Not detecting google assistant using my mic

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#84] opened 2021-01-19 05:45 UTC
when I say "ok google" and speak to the google assistant, Vigilante is not detecting that it is using the mic

**Comment by FunkyMuse** [comment] 2021-01-19 17:56
I tried the same thing, it doesn't detect it the first time you say "ok google" or "hey google"

It might be due to how assistants are implemented as they don't use the microphone at first rather they use an implementation called keyword spotting.

I'll look into that more, thanks for reporting this

**Comment by FunkyMuse** [comment] 2021-01-28 13:04
Yup that's the case as i've explained above, if anyone has a workaround for this on how to detect it, i'll be glad to implement it.

**Comment by FunkyMuse** [comment] 2021-02-01 20:31
I've been looking into this issue without any real solution or hacky solution, sadly I think it's due to the implementation of keyword spotting not firing up the microphone since Google usually comes with system permission, if you or someone else can try this with another assistant i'll be glad to get more insight since i'm currently busy with other projects.

**Comment by WAPEETY** [comment] 2021-06-18 20:48
Guys actually I don't have this issue, how can I reproduce this bug?

**Comment by FunkyMuse** [comment] 2021-06-18 20:56
> Guys actually I don't have this issue, how can I reproduce this bug?

It only happens if you say hello Google (hi Google), to activate it, afterwards the MIC is detected, the first time when you speak to it, Google doesn't uses only word spotting and the MIC fires afterwards, I'll be closing the issue since there's no fix for this.

**Closed by FunkyMuse** 2021-06-18 20:56 UTC
Labels: bug, help needed
